### ISSUE TITLE
program crashes when invalid direction entered

### ISSUE THREAD

**Issue by mineshkothari** [mineshkothari/adventure#1]
"D:\Program Files\Python 2.7.14\python.exe" D:/Documents/PycharmProjects/adventure/adventure.py
you are at the house
to the east is a park
to the south is a lake
which direction do you want to go?
east
you are at the park
to the west is a house
to the south is a market
which direction do you want to go?
north
Traceback (most recent call last):
  File "D:/Documents/PycharmProjects/adventure/adventure.py", line 25, in <module>
    position = valid_directions[direction]
KeyError: 'north'

Process finished with exit code 1

**Comment by alejandromorrison** [comment]
You can use too the try, for the python code to error handling exception.
